spring:
  datasource:
    password: 1234
    url: jdbc:mysql://localhost:3306/sales?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useTimezone=true&useLegacyDatetimeCode=false
    username: root
  jpa:
    hibernate:
      ddl-auto: create

  security:
    oauth2:
      client:
        registration:
         google:
          clientId: 976820423936-7achejc0qsathb4iuorhks44thr2lit2.apps.googleusercontent.com
          clientSecret: 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

          scope:
           - email
           - profile